### ISSUE TITLE
Error update last login date during login 

### ISSUE THREAD

**Issue by bgougent** [DaBourz/SimpleLoginSecure#12]
Replace 
`//$this->CI->db->simple_query('UPDATE ' . $this->user_table  . ' SET user_last_login = "' . date('c') . '" WHERE user_id = ' . $user_data['user_id']);`
with

`$data = array('user_last_login' => date('c'),);
$this->db->where('user_id',  $user_data['user_id']); 
$this->db->update($this->user_table, $data);`

when database has a prefix the update method in the file does not work

**Comment by mckaygerhard** [comment]
fixed with #13
