### ISSUE TITLE
CI-3.0dev problem with sess_create

### ISSUE THREAD

**Issue by jpruiz114** [DaBourz/SimpleLoginSecure#9]
This line:

$this->session->sess_create();

Must be changed to:

$this->session->sess_regenerate(TRUE);

Line 178 - File SimpleLoginSecure.php

**Comment by DaBourz** [comment]
Didn't had time until now, will update the whole thing with PHP, Mysql and CI 3

**Comment by DaBourz** [comment]
It's done and made for still working in both CI2 and CI 3
